# Generated by Django 3.0 on 2022-01-24 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=1080)),
                ('start_date', models.DateField(default=datetime.datetime(2022, 1, 24, 9, 30, 8, 567188, tzinfo=utc))),
            ],
        ),
    ]
