# Generated by Django 4.0 on 2022-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220124_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labour',
            name='project_name',
        ),
        migrations.AddField(
            model_name='labour',
            name='project_name',
            field=models.ManyToManyField(to='home.Project'),
        ),
    ]
