# Generated by Django 4.0 on 2022-01-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_labour_project_name_labour_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('project_name', models.ManyToManyField(to='home.Project')),
            ],
        ),
    ]
