# Generated by Django 4.0 on 2022-01-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='labour_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='diesel_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='labour_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='petrol_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='units_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='used_for',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=1080, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=1080, null=True),
        ),
        migrations.DeleteModel(
            name='Labour',
        ),
    ]
