# Generated by Django 4.0 on 2022-01-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_payment_labour_name_payment_bill_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='diesel_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='labour_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='petrol_amount',
            field=models.FloatField(default=0),
        ),
    ]
