# Generated by Django 4.0 on 2022-01-28 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_payment_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
    ]
