# Generated by Django 4.0 on 2022-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
