# Generated by Django 4.0 on 2022-02-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_payment_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('L', 'LIQUID'), ('P', 'POWDER'), ('LP', 'LIQUID and POWDER')], max_length=2, null=True),
        ),
    ]
