# Generated by Django 4.0 on 2022-02-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0020_remove_product_date_remove_product_product_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='diesel_used',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='petrol_used',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='units_used',
        ),
        migrations.AddField(
            model_name='payment',
            name='qty_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.project'),
        ),
    ]
