# Generated by Django 4.0 on 2022-02-22 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_payment_diesel_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1080)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='project_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.AddField(
            model_name='payment',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.crop'),
        ),
    ]
