# Generated by Django 4.0 on 2022-02-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_crop_remove_supervisor_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='container_size',
            new_name='volume',
        ),
    ]
