# Generated by Django 4.0 on 2022-02-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_container_size_product_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
    ]
