# Generated by Django 4.0 on 2022-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_payment_remarks_alter_payment_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='labour_used',
            new_name='female_labour_used',
        ),
        migrations.AddField(
            model_name='payment',
            name='male_labour_used',
            field=models.IntegerField(default=0),
        ),
    ]
