# Generated by Django 4.0.3 on 2022-04-03 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_remove_payment_labour_amount_crop_area_crop_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
