# Generated by Django 4.0.3 on 2022-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_crop_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='area',
            new_name='crop_area',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(max_length=1080, null=True, unique=True),
        ),
    ]
