# Generated by Django 4.0.3 on 2022-04-24 11:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0035_task_outward_products_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inward_product',
            new_name='InwardProduct',
        ),
        migrations.RenameModel(
            old_name='outward_products',
            new_name='OutwardProduct',
        ),
    ]
