# Generated by Django 4.0.3 on 2022-04-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_rename_inward_product_inwardproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outwardproduct',
            old_name='created_at',
            new_name='used_date',
        ),
    ]
