# Generated by Django 4.0.3 on 2022-05-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_outwardproduct_task_alter_outwardproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwardproduct',
            old_name='code',
            new_name='product_code',
        ),
    ]
