# Generated by Django 4.0.3 on 2022-05-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_outwardproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='outwardproduct',
            name='used_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
