# Generated by Django 4.0.3 on 2022-05-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_outwardproduct_used_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwardproduct',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
