# Generated by Django 4.0.3 on 2022-05-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_inwardproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwardproduct',
            old_name='price',
            new_name='price_init',
        ),
    ]
