# Generated by Django 4.0.3 on 2022-05-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_rename_price_inwardproduct_price_init'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inwardproduct',
            old_name='price_init',
            new_name='total_price',
        ),
    ]
