# Generated by Django 4.0.3 on 2022-05-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_rename_price_init_inwardproduct_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outwardproduct',
            old_name='price',
            new_name='price_used_product',
        ),
    ]
