# Generated by Django 4.0.3 on 2022-05-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_rename_price_outwardproduct_price_used_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outwardproduct',
            old_name='price_used_product',
            new_name='price',
        ),
    ]
