# Generated by Django 4.0.3 on 2022-05-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_labour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='female_amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='male_amount',
            field=models.FloatField(blank=True),
        ),
    ]
